In [12]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [13]:
#main function
from nltk import *
from nltk.tokenize import sent_tokenize, word_tokenize

if __name__ == '__main__':
    
    with open('joyToken.txt', 'r') as myfile:
        joy = myfile.read()
    joySentences = sent_tokenize(joy)
    
    with open('saddnessToken.txt', 'r') as myfile:
        saddness = myfile.read()
    saddnessSentences = sent_tokenize(saddness)
    
    with open('shameToken.txt', 'r') as myfile:
        shame = myfile.read()
    shameSentences = sent_tokenize(shame)
    
    with open('lexicon_dictionary.txt', 'r') as myfile:
        lexicon_dictionary = myfile.read()
    lexicon_dictionary = lexicon_dictionary.split('\n')
    a = 0
    for x in lexicon_dictionary :
        lexicon_dictionary[a] = x.split(' ')
        a = a + 1
    
    s = LancasterStemmer()
    unwantedWordes = ['the' , 'a', 'is' , 'was' , 'are',
                      'were' , 'to', 'at', 'i' , 'my',
                      'on' , 'me'  , 'of' , '.' , 'in' ,
                      'that' , 'he' , 'she' , 'it' , 'by']
    
    if not os.path.isfile('featureVectors.csv'):
        open('featureVectors.csv' , 'w')   
    with open('featureVectors.csv', 'w') as featuresFile:
            featuresFile.write('')
            
    for i in range(0, a - 1): 
        lexicon_dictionary[i][0] = s.stem(lexicon_dictionary[i][0])
    
    # create feature Vector to each sentences in joy file
    for x in joySentences:
        featureVector = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        words = word_tokenize(x)
        for y in words :
            y = s.stem(y)
            y = y.lower()
            if y in unwantedWordes != -1:
                continue
            for i in range(0, a - 1): 
                if y == lexicon_dictionary[i][0]:
                    for j in range(0, 10):
                        featureVector[j] = featureVector[j] + int (lexicon_dictionary[i][j + 1])
                    break
        featureVector.append(0)
        
        # write this feature vector to featureVectors File
        for k in range (0, 10):
            with open('featureVectors.csv', 'a') as featuresFile:
                featuresFile.write(str(featureVector[k]) + ',')
        with open('featureVectors.csv', 'a') as featuresFile:
            featuresFile.write(str(featureVector[10]) + '\n')
    
    # create feature Vector to each sentences in sadness file
    for x in saddnessSentences:
        featureVector = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        words = word_tokenize(x)
        for y in words :
            y = s.stem(y)
            y = y.lower()
            if y in unwantedWordes != -1:
                continue
            for i in range(0, a - 1): 
                if y == lexicon_dictionary[i][0]:
                    for j in range(0, 10):
                        featureVector[j] = featureVector[j] + int (lexicon_dictionary[i][j + 1])
                    break
        featureVector.append(1)
        
        # write this feature vector to featureVectors File
        for k in range (0, 10):
            with open('featureVectors.csv', 'a') as featuresFile:
                featuresFile.write(str(featureVector[k]) + ',')
        with open('featureVectors.csv', 'a') as featuresFile:
            featuresFile.write(str(featureVector[10]) + '\n')
    
    
    # create feature Vector to each sentences in shame file
    
    for x in shameSentences:
        featureVector = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        words = word_tokenize(x)
        for y in words :
            y = s.stem(y)
            y = y.lower()
            if y in unwantedWordes != -1:
                continue
            for i in range(0, a - 1): 
                if y == lexicon_dictionary[i][0]:
                    for j in range(0, 10):
                        featureVector[j] = featureVector[j] + int (lexicon_dictionary[i][j + 1])
                    break
        featureVector.append(2)
        
        # write this feature vector to featureVectors File
        for k in range (0, 10):
            with open('featureVectors.csv', 'a') as featuresFile:
                featuresFile.write(str(featureVector[k]) + ',')
        with open('featureVectors.csv', 'a') as featuresFile:
            featuresFile.write(str(featureVector[10]) + '\n')
    
    with open('featureVectors.csv', 'r') as myfile:
        features = myfile.read()
    features = features.split('\n')
    with open('featureVectors.csv', 'w') as featuresFile:
            featuresFile.write('')
    
    for i in range (0, 1040):
        with open('featureVectors.csv', 'a') as featuresFile:
            featuresFile.write(features[i] + '\n')
            featuresFile.write(features[i + 1040] + '\n')
            featuresFile.write(features[3117 - i] + '\n')
    
    
    pass

In [15]:
#Emotion of Sentences
from keras.models import model_from_json
import numpy
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem.lancaster import LancasterStemmer
import os

if __name__ == '__main__':  
    # enter Your Sentences in Sentences.txt File
    # Only code needed to  Load Code
    json_file = open("model.json", 'r')
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
    # load weights into new model
    model.load_weights("model.h5")
    print("Loaded model from disk")
    ###########################
    with open('lexicon_dictionary.txt', 'r') as myfile:
        lexicon_dictionary = myfile.read()
    lexicon_dictionary = lexicon_dictionary.split('\n')
    a = 0

    for x in lexicon_dictionary :
        lexicon_dictionary[a] = x.split(' ')
        a = a + 1
    
    with open('sentences.txt', 'r') as myfile:
        sen = myfile.read()
    sentences = sent_tokenize(sen)
    
    if not os.path.isfile('featureVectorForSentence.csv'):
        open('featureVectorForSentence.csv' , 'w')   
    with open('featureVectorForSentence.csv', 'w') as featuresFile:
            featuresFile.write('')
    
    s = LancasterStemmer()
    unwantedWordes = ['the' , 'a', 'is' , 'was' , 'are',
                      'were' , 'to', 'at', 'i' , 'my',
                      'on' , 'me'  , 'of' , '.' , 'in' ,
                      'that' , 'he' , 'she' , 'it' , 'by']
    for i in range(0, a - 1): 
        lexicon_dictionary[i][0] = s.stem(lexicon_dictionary[i][0])
    
    for x in sentences:
        featureVector = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        words = word_tokenize(x)
        for y in words :
            y = s.stem(y)
            y = y.lower()
            if y in unwantedWordes != -1:
                continue
            for i in range(0, a - 1): 
                if y == lexicon_dictionary[i][0]:
                    for j in range(0, 10):
                        featureVector[j] = featureVector[j] + int (lexicon_dictionary[i][j + 1])
                    break
        # write this feature vector to featureVectors File
        for k in range (0, 9):
            with open('featureVectorForSentence.csv', 'a') as featuresFile:
                featuresFile.write(str(featureVector[k]) + ',')
        with open('featureVectorForSentence.csv', 'a') as featuresFile:
            featuresFile.write(str(featureVector[9]) + '\n')
    # to avoid one Sentence Error
    for k in range (0, 9):
        with open('featureVectorForSentence.csv', 'a') as featuresFile:
                featuresFile.write(str(featureVector[k]) + ',')
    with open('featureVectorForSentence.csv', 'a') as featuresFile:
        featuresFile.write(str(featureVector[9]) + '\n')
        
    
    dataset = numpy.loadtxt("featureVectorForSentence.csv", delimiter=",")
    X = dataset[ :-1, :]
    
    predictions = model.predict(X)
    rounded = numpy.around(predictions, decimals=0)
    print (rounded)
    
    c = 1
    shame = 0 
    joy = 0 
    sadness = 0
    print("Emotions For Each Sentences in sentences.txt File")
    for x in rounded:
        if x[0] == 1 and x[1] == 0 and x[2] == 0:
            joy = joy + 1
            print("Sentence Number " + str(c) + " is JOY")
        elif x[0] == 0 and x[1] == 1 and x[2] == 0:
            sadness = sadness + 1
            print("Sentence Number " + str(c) + " is Sadness")
        elif x[0] == 0 and x[1] == 0 and x[2] == 1:
            shame = shame + 1
            print("Sentence Number " + str(c) + " is Shame")
        c = c + 1
    print ("Joy :" + str(joy))
    print ("sadness :" + str(sadness))
    print ("shame :" + str(shame))
    
    
    pass


Loaded model from disk
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
Emotions For Each Sentences in sentences.txt File
Sentence Number 2 is JOY
Sentence Number 3 is Shame
Sentence Number 4 is Sadness
Sentence Number 5 is Sadness
Sentence Number 6 is Sadness
Sentence Number 7 is Sadness
Sentence Number 8 is Shame
Sentence Number 9 is Shame
Joy :1
sadness :4
shame :3


In [16]:
#ML code for Feature Vectorization
from keras.models import Sequential
from keras.layers import Dense
from keras.utils.np_utils import to_categorical
import numpy

dataset = numpy.loadtxt("featureVectors.csv", delimiter=",")
# split into input (X) and output (Y) variables
# Train Set
X = dataset[:, 0:10]
y_int = dataset[:, 10:]
Y = to_categorical(y_int)

# Test Set
XTest = dataset[0:200, 0:10]
ytest_int = dataset[0:200, 10:]
yTest = to_categorical(ytest_int)
# create model
model = Sequential()
model.add(Dense(output_dim=100, init='uniform', activation='relu'   , input_dim=10))
model.add(Dense(output_dim=100 , init='uniform', activation='relu'   , input_dim=100))
model.add(Dense(output_dim=3   , init='uniform', activation='softmax', input_dim=100))
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


# Fit the model
model.fit(X, Y, nb_epoch=25, batch_size=10)
# evaluate the model
scores = model.evaluate(XTest, yTest)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))

# Train Set
X = dataset[:2900, 0:10]
y_int = dataset[:2900, 10:]
Y = to_categorical(y_int)
# Test Set
XTest = dataset[2900:, 0:10]
ytest_int = dataset[2900:, 10:]
yTest = to_categorical(ytest_int)
# Fit the model
model.fit(X, Y, nb_epoch=25, batch_size=10)
# evaluate the model
scores = model.evaluate(XTest, yTest)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1] * 100))


# #Only code needed to save model
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
model.save_weights("model.h5")
##################################

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=10, units=100, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=100, units=100, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", input_dim=100, units=3, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/25
3120/3120 [==============================] - 0s 140us/step - loss: 1.0417 - accuracy: 0.4439
Epoch 2/25
3120/3120 [==============================] - 0s 120us/step - loss: 0.9938 - accuracy: 0.5244
Epoch 3/25
3120/3120 [==============================] - 0s 115us/step - loss: 0.9760 - accuracy: 0.5308
Epoch 4/25
3120/3120 [==============================] - 0s 117us/step - loss: 0.9704 - accuracy: 0.5362
Epoch 5/25
3120/3120 [==============================] - 0s 111us/step - loss: 0.9607 - accuracy: 0.5375
Epoch 6/25
3120/3120 [==============================] - 0s 110us/step - loss: 0.9537 - accuracy: 0.5436
Epoch 7/25
3120/3120 [==============================] - 0s 111us/step - loss: 0.9525 - accuracy: 0.5413
Epoch 8/25
3120/3120 [==============================] - 0s 113us/step - loss: 0.9460 - accuracy: 0.5436
Epoch 9/25
3120/3120 [==============================] - 0s 117us/step - loss: 0.9417 - accuracy: 0.5413
Epoch 10/25
3120/3120 [==============================] - 0s 114u

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:42: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


2900/2900 [==============================] - 0s 117us/step - loss: 0.8841 - accuracy: 0.5741
Epoch 2/25
2900/2900 [==============================] - 0s 126us/step - loss: 0.8806 - accuracy: 0.5876
Epoch 3/25
2900/2900 [==============================] - 0s 120us/step - loss: 0.8759 - accuracy: 0.5841
Epoch 4/25
2900/2900 [==============================] - 0s 117us/step - loss: 0.8767 - accuracy: 0.5845
Epoch 5/25
2900/2900 [==============================] - 0s 118us/step - loss: 0.8678 - accuracy: 0.5859
Epoch 6/25
2900/2900 [==============================] - 0s 119us/step - loss: 0.8685 - accuracy: 0.5852
Epoch 7/25
2900/2900 [==============================] - 0s 121us/step - loss: 0.8607 - accuracy: 0.5945
Epoch 8/25
2900/2900 [==============================] - 0s 122us/step - loss: 0.8560 - accuracy: 0.5910
Epoch 9/25
2900/2900 [==============================] - 0s 123us/step - loss: 0.8540 - accuracy: 0.6024
Epoch 10/25
2900/2900 [==============================] - 0s 117us/step - lo